/**
 * AppGuard Demo Data
 * 
 * Realistic sample Android apps for demo mode.
 */

const DEMO_APPS = [
    {
        packageName: 'com.whatsapp',
        appLabel: 'WhatsApp',
        icon: '💬',
        iconBg: '#25D366',
        versionName: '2.24.10.79',
        installerPackage: 'com.android.vending',
        targetSdk: '34',
        isSystemApp: false,
        requestedPermissions: [
            'android.permission.CAMERA',
            'android.permission.RECORD_AUDIO',
            'android.permission.READ_CONTACTS',
            'android.permission.WRITE_CONTACTS',
            'android.permission.READ_EXTERNAL_STORAGE',
            'android.permission.WRITE_EXTERNAL_STORAGE',
            'android.permission.ACCESS_FINE_LOCATION',
            'android.permission.ACCESS_COARSE_LOCATION',
            'android.permission.READ_PHONE_STATE',
            'android.permission.INTERNET',
            'android.permission.RECEIVE_BOOT_COMPLETED',
            'android.permission.WAKE_LOCK',
        ],
        certificate: { isSelfSigned: true, isDebugSigned: false, isExpired: false },
    },
    {
        packageName: 'com.flashlight.super.bright',
        appLabel: 'Super Flashlight',
        icon: '🔦',
        iconBg: '#ff6b35',
        versionName: '3.1.2',
        installerPackage: '',
        targetSdk: '26',
        isSystemApp: false,
        requestedPermissions: [
            'android.permission.CAMERA',
            'android.permission.RECORD_AUDIO',
            'android.permission.READ_SMS',
            'android.permission.SEND_SMS',
            'android.permission.READ_CONTACTS',
            'android.permission.ACCESS_FINE_LOCATION',
            'android.permission.ACCESS_BACKGROUND_LOCATION',
            'android.permission.INTERNET',
            'android.permission.READ_PHONE_STATE',
            'android.permission.SYSTEM_ALERT_WINDOW',
            'android.permission.REQUEST_INSTALL_PACKAGES',
            'android.permission.READ_EXTERNAL_STORAGE',
            'android.permission.WRITE_EXTERNAL_STORAGE',
            'android.permission.MANAGE_EXTERNAL_STORAGE',
            'android.permission.RECEIVE_BOOT_COMPLETED',
        ],
        certificate: { isSelfSigned: true, isDebugSigned: true, isExpired: false },
    },
    {
        packageName: 'com.spotify.music',
        appLabel: 'Spotify',
        icon: '🎵',
        iconBg: '#1DB954',
        versionName: '8.9.42.575',
        installerPackage: 'com.android.vending',
        targetSdk: '34',
        isSystemApp: false,
        requestedPermissions: [
            'android.permission.INTERNET',
            'android.permission.ACCESS_NETWORK_STATE',
            'android.permission.WAKE_LOCK',
            'android.permission.RECEIVE_BOOT_COMPLETED',
            'android.permission.READ_EXTERNAL_STORAGE',
        ],
        certificate: { isSelfSigned: true, isDebugSigned: false, isExpired: false },
    },
    {
        packageName: 'com.calculator.simple',
        appLabel: 'Calculator',
        icon: '🔢',
        iconBg: '#6366f1',
        versionName: '1.0.3',
        installerPackage: 'com.android.vending',
        targetSdk: '33',
        isSystemApp: false,
        requestedPermissions: [
            'android.permission.INTERNET',
            'android.permission.ACCESS_NETWORK_STATE',
        ],
        certificate: { isSelfSigned: true, isDebugSigned: false, isExpired: false },
    },
    {
        packageName: 'com.shady.vpn.free',
        appLabel: 'FreeVPN Pro',
        icon: '🔐',
        iconBg: '#ef4444',
        versionName: '5.2.0',
        installerPackage: '',
        targetSdk: '29',
        isSystemApp: false,
        requestedPermissions: [
            'android.permission.INTERNET',
            'android.permission.ACCESS_NETWORK_STATE',
            'android.permission.CHANGE_NETWORK_STATE',
            'android.permission.ACCESS_FINE_LOCATION',
            'android.permission.ACCESS_BACKGROUND_LOCATION',
            'android.permission.READ_PHONE_STATE',
            'android.permission.READ_EXTERNAL_STORAGE',
            'android.permission.WRITE_EXTERNAL_STORAGE',
            'android.permission.CAMERA',
            'android.permission.QUERY_ALL_PACKAGES',
            'android.permission.RECEIVE_BOOT_COMPLETED',
            'android.permission.WAKE_LOCK',
        ],
        certificate: { isSelfSigned: true, isDebugSigned: false, isExpired: false },
    },
    {
        packageName: 'com.instagram.android',
        appLabel: 'Instagram',
        icon: '📸',
        iconBg: '#E4405F',
        versionName: '332.0.0.38.90',
        installerPackage: 'com.android.vending',
        targetSdk: '34',
        isSystemApp: false,
        requestedPermissions: [
            'android.permission.CAMERA',
            'android.permission.RECORD_AUDIO',
            'android.permission.READ_CONTACTS',
            'android.permission.ACCESS_FINE_LOCATION',
            'android.permission.ACCESS_COARSE_LOCATION',
            'android.permission.READ_EXTERNAL_STORAGE',
            'android.permission.WRITE_EXTERNAL_STORAGE',
            'android.permission.INTERNET',
            'android.permission.READ_PHONE_STATE',
            'android.permission.RECEIVE_BOOT_COMPLETED',
            'android.permission.WAKE_LOCK',
        ],
        certificate: { isSelfSigned: true, isDebugSigned: false, isExpired: false },
    },
    {
        packageName: 'com.tiktok.video',
        appLabel: 'TikTok',
        icon: '🎬',
        iconBg: '#010101',
        versionName: '34.5.3',
        installerPackage: 'com.android.vending',
        targetSdk: '34',
        isSystemApp: false,
        requestedPermissions: [
            'android.permission.CAMERA',
            'android.permission.RECORD_AUDIO',
            'android.permission.READ_CONTACTS',
            'android.permission.ACCESS_FINE_LOCATION',
            'android.permission.ACCESS_COARSE_LOCATION',
            'android.permission.READ_EXTERNAL_STORAGE',
            'android.permission.WRITE_EXTERNAL_STORAGE',
            'android.permission.INTERNET',
            'android.permission.READ_PHONE_STATE',
            'android.permission.RECEIVE_BOOT_COMPLETED',
            'android.permission.WAKE_LOCK',
            'android.permission.READ_CALENDAR',
            'android.permission.BODY_SENSORS',
        ],
        certificate: { isSelfSigned: true, isDebugSigned: false, isExpired: false },
    },
    {
        packageName: 'com.shady.cleaner.boost',
        appLabel: 'Super Cleaner Pro',
        icon: '🧹',
        iconBg: '#dc2626',
        versionName: '7.0.1',
        installerPackage: '',
        targetSdk: '25',
        isSystemApp: false,
        requestedPermissions: [
            'android.permission.READ_SMS',
            'android.permission.SEND_SMS',
            'android.permission.READ_CONTACTS',
            'android.permission.WRITE_CONTACTS',
            'android.permission.CAMERA',
            'android.permission.RECORD_AUDIO',
            'android.permission.ACCESS_FINE_LOCATION',
            'android.permission.ACCESS_BACKGROUND_LOCATION',
            'android.permission.INTERNET',
            'android.permission.READ_PHONE_STATE',
            'android.permission.CALL_PHONE',
            'android.permission.READ_CALL_LOG',
            'android.permission.SYSTEM_ALERT_WINDOW',
            'android.permission.REQUEST_INSTALL_PACKAGES',
            'android.permission.BIND_DEVICE_ADMIN',
            'android.permission.MANAGE_EXTERNAL_STORAGE',
            'android.permission.QUERY_ALL_PACKAGES',
            'android.permission.RECEIVE_BOOT_COMPLETED',
        ],
        certificate: { isSelfSigned: true, isDebugSigned: true, isExpired: true },
    },
];

window.DEMO_APPS = DEMO_APPS;
